package modelo;

public enum Evento {
    CONECTADO, ERROR, PROCESO_ANIADIDO, DIFUNDIDO_CORRECTO,
    RECIBIRMENSAJE, ENVIARMENSAJE, CREADO, REVIVIR, DORMIR,
    COMENZARELECCION, ACTUALIZARCOORDINADOR, ACTUALIZARMARCA,
    CONFIRMADO
}
